In [16]:
import kagglehub
import pandas as pd
import os

path = kagglehub.dataset_download("nishaanamin/march-madness-data")
path2 = kagglehub.dataset_download("andrewsundberg/college-basketball-dataset")
df1 = pd.read_csv(os.path.join(path, "538 Ratings.csv"))
df2 = pd.read_csv(os.path.join(path, "AP Poll Data.csv"))
df3 = pd.read_csv(os.path.join(path, "KenPom Barttorvik.csv"))
df4 = pd.read_csv(os.path.join(path2, "cbb.csv"))

In [11]:
df1

,YEAR,TEAM NO,TEAM,SEED,ROUND,POWER RATING,POWER RATING RANK
0,2024,1067,Connecticut,1,1,95.6,4
1,2024,1056,Houston,1,16,94.9,8
2,2024,1033,Purdue,1,2,93.5,15
3,2024,1038,North Carolina,1,16,90.2,49
4,2024,1077,Arizona,2,16,91.6,29
...,...,...,...,...,...,...,...
539,2016,602,Austin Peay,16,64,68.8,527
540,2016,585,Hampton,16,64,68.6,529
541,2016,558,Southern,16,68,68.0,532
542,2016,583,Holy Cross,16,64,66.8,538
543,2016,590,Fairleigh Dickinson,16,68,66.7,539

In [12]:
df2

,YEAR,WEEK,TEAM NO,TEAM,SEED,ROUND,W,L,AP VOTES,AP RANK,RANK?
0,2026,1,1173.0,Purdue,2.0,0.0,0.0,0.0,1485.0,1.0,1
1,2026,1,1199.0,Houston,2.0,0.0,0.0,0.0,1459.0,2.0,1
2,2026,1,1206.0,Florida,1.0,0.0,0.0,0.0,1382.0,3.0,1
3,2026,1,1208.0,Connecticut,2.0,0.0,0.0,0.0,1299.0,4.0,1
4,2026,1,1165.0,St. John's,5.0,0.0,0.0,0.0,1203.0,5.0,1
...,...,...,...,...,...,...,...,...,...,...,...
16190,2008,20,46.0,Georgia,14.0,64.0,NaN,NaN,2.0,38.0,0
16191,2008,20,23.0,Saint Joseph's,11.0,64.0,NaN,NaN,2.0,38.0,0
16192,2008,20,59.0,Boise St.,14.0,64.0,NaN,NaN,1.0,40.0,0
16193,2008,20,19.0,South Alabama,10.0,64.0,NaN,NaN,1.0,40.0,0
16194,2008,20,12.0,UMBC,15.0,64.0,NaN,NaN,1.0,40.0,0

In [18]:
df3

,YEAR,CONF,CONF ID,QUAD NO,QUAD ID,TEAM NO,TEAM ID,TEAM,SEED,ROUND,...,BADJT RANK,AVG HGT RANK,EFF HGT RANK,EXP RANK,TALENT RANK,FT% RANK,OP FT% RANK,PPPO RANK,PPPD RANK,ELITE SOS RANK
0,2026,MAC,17,69,1,1215,2,Akron,12,0,...,34,362,363,38,164,73,174,6,86,263
1,2026,SEC,28,69,1,1214,3,Alabama,4,0,...,4,89,76,294,8,42,47,5,249,6
2,2026,B12,7,70,2,1213,8,Arizona,1,0,...,43,8,26,324,9,158,130,15,5,10
3,2026,SEC,28,70,2,1212,10,Arkansas,4,0,...,23,30,49,309,6,99,162,4,201,13
4,2026,B12,7,70,2,1211,25,BYU,6,0,...,58,70,98,307,48,100,117,29,124,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1210,2008,BE,8,1,1,5,235,West Virginia,7,16,...,225,18,115,181,61,209,16,22,32,49
1211,2008,SB,26,1,1,4,236,Western Kentucky,12,16,...,111,160,179,55,131,127,214,27,28,203
1212,2008,BSth,10,4,4,3,239,Winthrop,13,64,...,301,231,206,89,236,339,190,170,12,179
1213,2008,B10,6,3,3,2,240,Wisconsin,3,16,...,301,51,35,98,12,118,117,60,2,57
1214,2008,A10,1,1,1,1,244,Xavier,3,8,...,225,149,92,63,147,20,86,4,44,85

In [17]:
df4

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,YEAR
0,North Carolina,ACC,40,33,123.3,94.9,0.9531,52.6,48.1,15.4,...,30.4,53.9,44.6,32.7,36.2,71.7,8.6,2ND,1.0,2016
1,Wisconsin,B10,40,36,129.1,93.6,0.9758,54.8,47.7,12.4,...,22.4,54.8,44.7,36.5,37.5,59.3,11.3,2ND,1.0,2015
2,Michigan,B10,40,33,114.4,90.4,0.9375,53.9,47.7,14.0,...,30.0,54.7,46.8,35.2,33.2,65.9,6.9,2ND,3.0,2018
3,Texas Tech,B12,38,31,115.2,85.2,0.9696,53.5,43.0,17.7,...,36.6,52.8,41.9,36.5,29.7,67.5,7.0,2ND,3.0,2019
4,Gonzaga,WCC,39,37,117.8,86.3,0.9728,56.6,41.1,16.2,...,26.9,56.3,40.0,38.2,29.0,71.5,7.7,2ND,1.0,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4244,The Citadel,SC,30,5,94.0,117.6,0.0705,46.9,54.5,19.5,...,32.8,49.5,56.3,29.2,34.7,64.8,-21.4,NaN,NaN,2025
4245,Chicago St.,NEC,32,4,92.8,116.4,0.0688,44.4,54.9,18.5,...,36.9,43.4,55.7,30.6,35.8,68.8,-21.7,NaN,NaN,2025
4246,Arkansas Pine Bluff,SWAC,31,6,95.3,121.8,0.0563,50.3,56.3,20.4,...,40.5,52.6,58.5,31.0,35.7,71.8,-20.0,NaN,NaN,2025
4247,Coppin St.,MEAC,30,6,88.0,112.6,0.0556,44.0,55.6,21.6,...,37.1,44.2,56.3,29.0,36.3,68.2,-19.0,NaN,NaN,2025
4248,Mississippi Valley St.,SWAC,31,3,83.1,125.3,0.0088,42.1,57.9,24.3,...,38.4,41.6,58.8,28.8,37.7,65.1,-21.0,NaN,NaN,2025

['YEAR', 'TEAM NO', 'TEAM', 'SEED', 'ROUND', 'POWER RATING', 'POWER RATING RANK']
['YEAR', 'WEEK', 'TEAM NO', 'TEAM', 'SEED', 'ROUND', 'W', 'L', 'AP VOTES', 'AP RANK', 'RANK?']
['YEAR', 'CONF', 'CONF ID', 'QUAD NO', 'QUAD ID', 'TEAM NO', 'TEAM ID', 'TEAM', 'SEED', 'ROUND', 'K TEMPO', 'K TEMPO RANK', 'KADJ T', 'KADJ T RANK', 'K OFF', 'KO RANK', 'KADJ O', 'KADJ O RANK', 'K DEF', 'KD RANK', 'KADJ D', 'KADJ D RANK', 'KADJ EM', 'KADJ EM RANK', 'BADJ EM', 'BADJ O', 'BADJ D', 'BARTHAG', 'GAMES', 'W', 'L', 'WIN%', 'EFG%', 'EFG%D', 'FTR', 'FTRD', 'TOV%', 'TOV%D', 'OREB%', 'DREB%', 'OP OREB%', 'OP DREB%', 'RAW T', '2PT%', '2PT%D', '3PT%', '3PT%D', 'BLK%', 'BLKED%', 'AST%', 'OP AST%', '2PTR', '3PTR', '2PTRD', '3PTRD', 'BADJ T', 'AVG HGT', 'EFF HGT', 'EXP', 'TALENT', 'FT%', 'OP FT%', 'PPPO', 'PPPD', 'ELITE SOS', 'WAB', 'BADJ EM RANK', 'BADJ O RANK', 'BADJ D RANK', 'BARTHAG RANK', 'EFG% RANK', 'EFGD% RANK', 'FTR RANK', 'FTRD RANK', 'TOV% RANK', 'TOV%D RANK', 'OREB% RANK', 'DREB% RANK', 'OP OREB% RANK', 'OP DREB% RANK', 'RAW T RANK', '2PT% RANK', '2PT%D RANK', '3PT% RANK', '3PT%D RANK', 'BLK% RANK', 'BLKED% RANK', 'AST% RANK', 'OP AST% RANK', '2PTR RANK', '3PTR RANK', '2PTRD RANK', '3PTRD RANK', 'BADJT RANK', 'AVG HGT RANK', 'EFF HGT RANK', 'EXP RANK', 'TALENT RANK', 'FT% RANK', 'OP FT% RANK', 'PPPO RANK', 'PPPD RANK', 'ELITE SOS RANK']
['TEAM', 'CONF', 'G', 'W', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D', 'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O', '3P_D', 'ADJ_T', 'WAB', 'POSTSEASON', 'SEED', 'YEAR']